# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_services_demo/protos/user.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='grpc_services_demo/protos/user.proto',
    package='',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=b'\n$grpc_services_demo/protos/user.proto\"\"\n\x0bUserRequest\x12\x13\n\x0bsearch_term\x18\x01 \x01(\t\"A\n\tUserReply\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x10\n\x08group_id\x18\x03 \x01(\t2,\n\x04User\x12$\n\x06Search\x12\x0c.UserRequest\x1a\n.UserReply\"\x00\x62\x06proto3'
)

_USERREQUEST = _descriptor.Descriptor(
    name='UserRequest',
    full_name='UserRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='search_term', full_name='UserRequest.search_term', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=40,
    serialized_end=74,
)

_USERREPLY = _descriptor.Descriptor(
    name='UserReply',
    full_name='UserReply',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='user_name', full_name='UserReply.user_name', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='user_id', full_name='UserReply.user_id', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='group_id', full_name='UserReply.group_id', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=76,
    serialized_end=141,
)

DESCRIPTOR.message_types_by_name['UserRequest'] = _USERREQUEST
DESCRIPTOR.message_types_by_name['UserReply'] = _USERREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserRequest = _reflection.GeneratedProtocolMessageType('UserRequest', (_message.Message,), {
    'DESCRIPTOR': _USERREQUEST,
    '__module__': 'grpc_services_demo.protos.user_pb2'
    # @@protoc_insertion_point(class_scope:UserRequest)
})
_sym_db.RegisterMessage(UserRequest)

UserReply = _reflection.GeneratedProtocolMessageType('UserReply', (_message.Message,), {
    'DESCRIPTOR': _USERREPLY,
    '__module__': 'grpc_services_demo.protos.user_pb2'
    # @@protoc_insertion_point(class_scope:UserReply)
})
_sym_db.RegisterMessage(UserReply)

_USER = _descriptor.ServiceDescriptor(
    name='User',
    full_name='User',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=143,
    serialized_end=187,
    methods=[
        _descriptor.MethodDescriptor(
            name='Search',
            full_name='User.Search',
            index=0,
            containing_service=None,
            input_type=_USERREQUEST,
            output_type=_USERREPLY,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_USER)

DESCRIPTOR.services_by_name['User'] = _USER

# @@protoc_insertion_point(module_scope)
