# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import time

import grpc

from grpc_services_demo.user.grpc_services_demo.protos import user_pb2 as grpc__services__demo_dot_protos_dot_user__pb2, \
    user_pb2


class UserStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
            '/User/Search',
            request_serializer=grpc__services__demo_dot_protos_dot_user__pb2.UserRequest.SerializeToString,
            response_deserializer=grpc__services__demo_dot_protos_dot_user__pb2.UserReply.FromString,
        )


class UserServicer(object):
    """The greeting service definition.
    """

    def Search(self, request, context):
        """Sends a greeting
        """
        print(f'Received a search request at time: {time.asctime()}')
        response = user_pb2.UserReply()
        response.group_id = "12"
        response.user_name = "Rodolfo Olivieri"
        response.user_id = "1234"
        return response


def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Search': grpc.unary_unary_rpc_method_handler(
            servicer.Search,
            request_deserializer=grpc__services__demo_dot_protos_dot_user__pb2.UserRequest.FromString,
            response_serializer=grpc__services__demo_dot_protos_dot_user__pb2.UserReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
