# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_services_demo/protos/department.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='grpc_services_demo/protos/department.proto',
    package='',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=b'\n*grpc_services_demo/protos/department.proto\"(\n\x11\x44\x65partmentRequest\x12\x13\n\x0bsearch_term\x18\x01 \x01(\t\"R\n\x0f\x44\x65partmentReply\x12\x17\n\x0f\x64\x65partment_name\x18\x01 \x01(\t\x12\x15\n\rdepartment_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t2>\n\nDepartment\x12\x30\n\x06Search\x12\x12.DepartmentRequest\x1a\x10.DepartmentReply\"\x00\x62\x06proto3'
)

_DEPARTMENTREQUEST = _descriptor.Descriptor(
    name='DepartmentRequest',
    full_name='DepartmentRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='search_term', full_name='DepartmentRequest.search_term', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=46,
    serialized_end=86,
)

_DEPARTMENTREPLY = _descriptor.Descriptor(
    name='DepartmentReply',
    full_name='DepartmentReply',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='department_name', full_name='DepartmentReply.department_name', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='department_id', full_name='DepartmentReply.department_id', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='user_id', full_name='DepartmentReply.user_id', index=2,
            number=3, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=88,
    serialized_end=170,
)

DESCRIPTOR.message_types_by_name['DepartmentRequest'] = _DEPARTMENTREQUEST
DESCRIPTOR.message_types_by_name['DepartmentReply'] = _DEPARTMENTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DepartmentRequest = _reflection.GeneratedProtocolMessageType('DepartmentRequest', (_message.Message,), {
    'DESCRIPTOR': _DEPARTMENTREQUEST,
    '__module__': 'grpc_services_demo.protos.department_pb2'
    # @@protoc_insertion_point(class_scope:DepartmentRequest)
})
_sym_db.RegisterMessage(DepartmentRequest)

DepartmentReply = _reflection.GeneratedProtocolMessageType('DepartmentReply', (_message.Message,), {
    'DESCRIPTOR': _DEPARTMENTREPLY,
    '__module__': 'grpc_services_demo.protos.department_pb2'
    # @@protoc_insertion_point(class_scope:DepartmentReply)
})
_sym_db.RegisterMessage(DepartmentReply)

_DEPARTMENT = _descriptor.ServiceDescriptor(
    name='Department',
    full_name='Department',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=172,
    serialized_end=234,
    methods=[
        _descriptor.MethodDescriptor(
            name='Search',
            full_name='Department.Search',
            index=0,
            containing_service=None,
            input_type=_DEPARTMENTREQUEST,
            output_type=_DEPARTMENTREPLY,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_DEPARTMENT)

DESCRIPTOR.services_by_name['Department'] = _DEPARTMENT

# @@protoc_insertion_point(module_scope)
