# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import time

import grpc

from grpc_services_demo.department.grpc_services_demo.protos import \
    department_pb2 as grpc__services__demo_dot_protos_dot_department__pb2, department_pb2


class DepartmentStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
            '/Department/Search',
            request_serializer=grpc__services__demo_dot_protos_dot_department__pb2.DepartmentRequest.SerializeToString,
            response_deserializer=grpc__services__demo_dot_protos_dot_department__pb2.DepartmentReply.FromString,
        )


class DepartmentServicer(object):
    """The greeting service definition.
    """

    def Search(self, request, context):
        """Sends a greeting
        """
        print(f'Received a search request at time: {time.asctime()}')
        response = department_pb2.DepartmentReply()
        response.department_id = "12345678"
        response.department_name = "Department test"
        response.user_id = "1234"
        return response


def add_DepartmentServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Search': grpc.unary_unary_rpc_method_handler(
            servicer.Search,
            request_deserializer=grpc__services__demo_dot_protos_dot_department__pb2.DepartmentRequest.FromString,
            response_serializer=grpc__services__demo_dot_protos_dot_department__pb2.DepartmentReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Department', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
