# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_services_demo/protos/category.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc_services_demo/protos/category.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n(grpc_services_demo/protos/category.proto\"&\n\x0f\x43\x61tegoryRequest\x12\x13\n\x0bsearch_term\x18\x01 \x01(\t\"L\n\rCategoryReply\x12\x15\n\rcategory_name\x18\x01 \x01(\t\x12\x13\n\x0b\x63\x61tegory_id\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t28\n\x08\x43\x61tegory\x12,\n\x06Search\x12\x10.CategoryRequest\x1a\x0e.CategoryReply\"\x00\x62\x06proto3'
)




_CATEGORYREQUEST = _descriptor.Descriptor(
  name='CategoryRequest',
  full_name='CategoryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='search_term', full_name='CategoryRequest.search_term', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=82,
)


_CATEGORYREPLY = _descriptor.Descriptor(
  name='CategoryReply',
  full_name='CategoryReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='category_name', full_name='CategoryReply.category_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='category_id', full_name='CategoryReply.category_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='CategoryReply.user_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=160,
)

DESCRIPTOR.message_types_by_name['CategoryRequest'] = _CATEGORYREQUEST
DESCRIPTOR.message_types_by_name['CategoryReply'] = _CATEGORYREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CategoryRequest = _reflection.GeneratedProtocolMessageType('CategoryRequest', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORYREQUEST,
  '__module__' : 'grpc_services_demo.protos.category_pb2'
  # @@protoc_insertion_point(class_scope:CategoryRequest)
  })
_sym_db.RegisterMessage(CategoryRequest)

CategoryReply = _reflection.GeneratedProtocolMessageType('CategoryReply', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORYREPLY,
  '__module__' : 'grpc_services_demo.protos.category_pb2'
  # @@protoc_insertion_point(class_scope:CategoryReply)
  })
_sym_db.RegisterMessage(CategoryReply)



_CATEGORY = _descriptor.ServiceDescriptor(
  name='Category',
  full_name='Category',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=162,
  serialized_end=218,
  methods=[
  _descriptor.MethodDescriptor(
    name='Search',
    full_name='Category.Search',
    index=0,
    containing_service=None,
    input_type=_CATEGORYREQUEST,
    output_type=_CATEGORYREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CATEGORY)

DESCRIPTOR.services_by_name['Category'] = _CATEGORY

# @@protoc_insertion_point(module_scope)
