# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_services_demo/protos/category.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name='grpc_services_demo/protos/category.proto',
    package='',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=b'\n(grpc_services_demo/protos/category.proto\x1a\x1cgoogle/protobuf/struct.proto\"&\n\x0f\x43\x61tegoryRequest\x12\x13\n\x0b\x63\x61tegory_id\x18\x01 \x01(\t\"=\n\rCategoryReply\x12,\n\x0b\x63\x61tegory_id\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct28\n\x08\x43\x61tegory\x12,\n\x06Search\x12\x10.CategoryRequest\x1a\x0e.CategoryReply\"\x00\x62\x06proto3'
    ,
    dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR, ])

_CATEGORYREQUEST = _descriptor.Descriptor(
    name='CategoryRequest',
    full_name='CategoryRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='category_id', full_name='CategoryRequest.category_id', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=74,
    serialized_end=112,
)

_CATEGORYREPLY = _descriptor.Descriptor(
    name='CategoryReply',
    full_name='CategoryReply',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='category_id', full_name='CategoryReply.category_id', index=0,
            number=1, type=11, cpp_type=10, label=1,
            has_default_value=False, default_value=None,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=114,
    serialized_end=175,
)

_CATEGORYREPLY.fields_by_name['category_id'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['CategoryRequest'] = _CATEGORYREQUEST
DESCRIPTOR.message_types_by_name['CategoryReply'] = _CATEGORYREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CategoryRequest = _reflection.GeneratedProtocolMessageType('CategoryRequest', (_message.Message,), {
    'DESCRIPTOR': _CATEGORYREQUEST,
    '__module__': 'grpc_services_demo.protos.category_pb2'
    # @@protoc_insertion_point(class_scope:CategoryRequest)
})
_sym_db.RegisterMessage(CategoryRequest)

CategoryReply = _reflection.GeneratedProtocolMessageType('CategoryReply', (_message.Message,), {
    'DESCRIPTOR': _CATEGORYREPLY,
    '__module__': 'grpc_services_demo.protos.category_pb2'
    # @@protoc_insertion_point(class_scope:CategoryReply)
})
_sym_db.RegisterMessage(CategoryReply)

_CATEGORY = _descriptor.ServiceDescriptor(
    name='Category',
    full_name='Category',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=177,
    serialized_end=233,
    methods=[
        _descriptor.MethodDescriptor(
            name='Search',
            full_name='Category.Search',
            index=0,
            containing_service=None,
            input_type=_CATEGORYREQUEST,
            output_type=_CATEGORYREPLY,
            serialized_options=None,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_CATEGORY)

DESCRIPTOR.services_by_name['Category'] = _CATEGORY

# @@protoc_insertion_point(module_scope)
